name: Push to S3
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
          aws-region: us-east-2

      - name: Create Repository Subfolder
        run: |
          REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
          aws s3api put-object --bucket learn-lesson-assets --key "$REPO_NAME/"

      - name: Get Modified and New Asset Files
        id: changes
        run: |
          if git rev-parse --verify HEAD^ >/dev/null 2>&1; then
            MODIFIED_AND_NEW_FILES=$(git diff --name-only --diff-filter=AM HEAD^ -- assets/)
          else
            MODIFIED_AND_NEW_FILES=$(git ls-files assets/)
          fi
          echo "::set-output name=modified_and_new_files::$MODIFIED_AND_NEW_FILES"

      - name: Sync Modified assets to S3 bucket
        run: |
          REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
          MODIFIED_AND_NEW_FILES=${{ steps.changes.outputs.modified_and_new_files }}

          for file in $MODIFIED_AND_NEW_FILES; do
            aws s3 cp "$file" "s3://learn-lesson-assets/$REPO_NAME/$(basename $file)"
          done
